---
# tasks file for hadoop
- name: Copy the custom file
  template:
    src: hadoop.j2
    dest: /tmp/hadoop

- name: hadoop deploy
  command: helm install stable/hadoop --values /tmp/hadoop --name {{ hadoop_name }} 

- name: wait
  pause:
    minutes: 2

- name:  users creation
  command: kubectl exec   {{ hadoop_name }}-hadoop-yarn-nm-0  -- /bin/sh -c "useradd  regprocessor;useradd  prereg;useradd idrepo"
    
- name: folder regrocessor
  command: kubectl exec   {{ hadoop_name }}-hadoop-yarn-nm-0  -- /bin/sh -c "hdfs dfs -mkdir /user;hdfs dfs -mkdir /user/regprocessor;hdfs dfs -chown -R regprocessor:regprocessor  /user/regprocessor" 
    
- name: folder prereg
  command: kubectl exec   {{ hadoop_name }}-hadoop-yarn-nm-0  -- /bin/sh -c "hdfs dfs -mkdir /user/prereg;hdfs dfs -chown -R prereg:prereg  /user/prereg"
    
- name: folder idrepo
  command: kubectl exec   {{ hadoop_name }}-hadoop-yarn-nm-0  -- /bin/sh -c "hdfs dfs -mkdir /user/idrepo;hdfs dfs -chown -R idrepo:idrepo  /user/idrepo"
